### ISSUE TITLE
Downloading images from R Studio

### ISSUE THREAD

**Issue by alexander-newton** [ministryofjustice/analytics-platform#100]
If you export an image from R Studio as a .png or .jpg (probably other formats too) the virus scanner always flags it and stops your from downloading. Current workaround is to save as a .txt and then change it back once downloaded.

**Comment by davidread** [comment]
I just tried this on my macbook and didn't have an issue. Is this virus checker a DOM1 thing, or something?

It would also be useful to understand what the reason is you're downloading image to your machine.

Useful to know the workaround.

**Comment by alexander-newton** [comment]
I'm on DOM1 so could well be. I'm downloading graphs, which have been saved as images, from R studio. Interestingly, if you then .zip up multiple images and download them you can download the .zip but you can't then open the images within. 

Others have confirmed this bug with me .

**Comment by davidread** [comment]
@alexander-newton we've had a chat about this and appreciate knowing about this issue of using AP on DOM1. However it's difficult to see a good way to improve this. The work-around isn't too difficult for users, fixing DOM1 is a huge task. Using AP for this sort of casual work of producing the odd graph is nice, but the core aim for AP is to support RAP-style analysis work, where the graphs are embedded in an app or HTML output, rather than downloaded for manual use. So I think given these constraints we'll not prioritize work on it right now, and leave it hear as a known limitation. Closed but not solved.
