### ISSUE TITLE
App build fails with message about the label

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform#115]
An app build fails with message about the label:

> Error: UPGRADE FAILED: Deployment.apps "criminal-fines-app-webapp" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"criminal-fines-app-webapp"}: `selector` does not match template `labels`

https://concourse.services.alpha.mojanalytics.xyz/teams/main/pipelines/criminal-fines-app/jobs/deploy/builds/20

First seen in build on 5/12/19

**Comment by xoen** [comment]
This is caused by this "bug"/constrain in k8s which disallow mutating labels: https://github.com/kubernetes/kubernetes/issues/26202#issuecomment-357518145

I've reverted the webapp change to the labels recently which should help: https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/414

**Comment by xoen** [comment]
I'm closing this issue and we can always keep an eye on it. We may or may not get few more of these errors but hopefully not (play with the labels could be a feasible workaround)

**Comment by davidread** [comment]
@sh31 says it's fixed in the chart. Not sure if it is fixed for the next build of this app though - need to check. And if it is fails we can add the label manually.

**Comment by davidread** [comment]
This has built fine the following time too, so all good now. Thanks @xoen
