### ISSUE TITLE
"create app" button not working

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#23]
The create app button doesn't appear to do anything...
![create3](https://user-images.githubusercontent.com/2608005/35735331-3b351062-081c-11e8-88a3-8dcc6b7b7623.gif)

I've tried to debug in Chrome it looked like it wasn't sending any web requests

**Comment by RobinL** [comment]
Hang on a sec, fixing the gif :-p

**Comment by RobinL** [comment]
Note type ahead didn't work on IMB tool

**Comment by axemonkey** [comment]
It doesn't send any XHR requests – the repo url/description data is prefetched server-side and fed to the page at render time. The problem here is that if the type-ahead doesn't match anything, then the URL is considered not-valid, since that means (in theory) the repo doesn't exist in the org. This means we don't technically allow free-typed URLs.

Looking at the moment, there is no `IMB-tool` repo in the analytics org.

**Comment by RobinL** [comment]
Ah, ok.  So the problem is that: `https://github.com/moj-analytical-services/IMB-tool` _does_ exist, but you can't see it because it's a private repo.  Note that I can see it.

So I guess two options:
- If it's easy, then enable the autofill to be populated with a list of all repos, including private.
- If not, then allow free typed repo URLs

My guess is that adding support for checking which repos the user can see (including private repos) may be quite complex, so I'd suggest at this time it might not be worth the effort.

Does that all make sense?

**Comment by axemonkey** [comment]
Hmmm. Yes it does make sense, but I was pretty sure Andy's repo-info-fetching work fetched all the private repos as well as public, since most of the repos in the analytics org are private.

_checks_

Yes, I can add https://github.com/moj-analytical-services/crest_engineering_draft for example, which is marked as a private repo. I can also see it on github, so in theory I should be able to see all private repos in the org (I think).

Hmmm. Looks like something else is happening here.
