### ISSUE TITLE
Issues using superuser rights to add users to apps

### ISSUE THREAD

**Issue by HaydenSansum** [ministryofjustice/analytics-platform#66]
When i try to add users to the `Possession-Visualisation` app I get the following error:

```
500 - "

Server Error (500)
"
```

This didn't occur when I tested adding users to a different app (`laa-cm-dashboard`) but does occur every time on the possession app

**Comment by davidread** [comment]
I have fixed the issue with this specific app and can successfully add an App Customer to it:
https://cpanel-master.services.alpha.mojanalytics.xyz/apps/58

The problem was that the app's Auth0 authorization group was not created. This should be created when the App is created in control panel. In a quick look I'm not sure what went wrong (nor can I see with a quick look in the code where this occurs).

I created the group in Auth0 manually. In future can probably be fixed in control panel by the user by deleting the app and creating it again.

I'll look more into this if it starts happening more often.
