### ISSUE TITLE
"hadabend" error in rstudio

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform#72]
## What happened?

When I started R Studio today I saw and error about "hadabend":
<img width="742" alt="screen shot 2018-10-08 at 13 56 53" src="https://user-images.githubusercontent.com/307612/46610369-1a7f8680-cafa-11e8-975a-1165a6116708.png">

I can still use R Studio fine, but logging it here.

Also, RT saw this as well today:

> when the bend occurs, it kicks me back to the previous project I had open

## Steps to reproduce the problem

?

## Workaround

RL says:
> Might be worth moving you `.rstudio` folder in your home directory
> e.g. `mv .rstudio .rstudiobu

**Comment by xoen** [comment]
This is mind-bending ahaha

**Comment by xoen** [comment]
There is a mentioned to this in the [platform_user_guidance](https://moj-analytical-services.github.io/platform_user_guidance/common-errors-and-solutions.html#rsession-username-error-session-hadabend) (which BTW is the second result for "session hadabend" on [google](https://www.google.co.uk)).

First result is [this RStudio support post](https://support.rstudio.com/hc/en-us/community/posts/200652816-R-Studio-Server-session-hadabend-). It seems indeed caused by RStudio struggling to restore a previous/crashed session.

[Workaround](https://github.com/Homebrew/homebrew-science/issues/5504#issuecomment-342977902) seems to to be delete `~/.rstudio` with `rm -rf ~/.rstudio` (which also includes some RStudio configuration)

**Comment by davidread** [comment]
Thanks @xoen. I'm closing this as the problem with R Studio, not AP, and we have an explanation & work-around now.
