### ISSUE TITLE
App login link expiry time too short

### ISSUE THREAD

**Issue by hbutcherMOJ** [ministryofjustice/analytics-platform#87]
Quantum is slow and sometimes the email with the link to login to an AP app does not arrive before it has expired.

Can we increase this time limit?

**Comment by chloepugh** [comment]
I've had feedback on an AP app from Quantum users that they sometimes find it difficult to log in as well

**Comment by davidread** [comment]
Thanks for raising this. This issue was discussed with @chloepugh on 13th December and @r4vi increased the email link timeout from 5 minutes to 30 minutes. I've tested it and it works.

I've now just adjusted the text in the email to reflect that timeout too.

I'll just note and comment on some other related concerns:

* it's tiresome to sign in to an app by going via your email - raised by @chloepugh. We're thinking about allowing AP users to login the normal way. Other customers though, would need more thought. 
* if you click the link and you're already logged into AP (not sure which domains) then you get the Auth0 error page saying "Unauthorized". Workaround is to use incognito mode. We can dig into this further if it causes continued grief. Raised by @chloepugh 
* some customers have corporate email accounts which have links scanned, essentially clicking the link, which means by the time the user clicks on the link it doesn't work any more, and they get the Auth0 error page saying "Unauthorized". (I think this was raised another time)
* apps often will 'grey out' and then either reconnect or needs to be reloaded. This is particularly troubling on apps like bentham where files are uploaded to the app. This is due to websocket connectivity issues, separate to sign in process and timeouts. Raised by @joeprinold

Feel free to come back to us on Slack, either to discuss further or to petition for us to raise the priority to work on them.
