### ISSUE TITLE
R Studio terminal occasionally hangs with websocket error

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform#89]
> Error: ```[2019-01-28 10:26:02] [error] handle_read_frame error: websocketpp.transport:7 (End of File)```
> I think this is what I get when my RStudio Terminal hangs and won't accept commands (everything else works it's no biggie). (BL)

Others said:
> I see (and ignore) this one often. (RI)

## Workarounds

* Open a new terminal (Alt+Shift+R) and close the frozen one.
* You can turn off R Studio's use of websockets in R Studio in the preferences, which should avoid this occurring

**Comment by MeganStodel** [comment]
FYI I've been seeing this for the first time today, fixed by closing terminal.

**Comment by ben-lavelle** [comment]
Just to note I get this probably more than 'occasionally', and often run up 4-5 terminals to call a couple of terminal commands--I expect to get it every session many times. 

Whilst usually just an irritation, it can cause more serious problems if it hangs **in the middle** of a process; I had it today in the middle of a complicated merge commit (while git had opened Vim for editing the merge message) that caused real headache and rework, and in the past have had it on delicate `cherry-pick`s (in the middle of choosing commits in Vim) that I've ended up abandoning because of this error.

**Comment by ghuiber** [comment]
This happens to me occasionally too, when I resume work on a long-running project. I think I know what causes it. In the project folder, in addition to the `<project_name>.Rproj` file, there is a hidden folder called `.Rproj.user` which tends to accumulate all kinds of cruft over time. I just `sudo rm -Rf` the thing. It is rebuilt every time you re-launch the project if it's not already present. This fixes the hanging terminal issue and a related issue where besides the hanging terminal I cannot close RStudio other than by force-quitting it. I am on a Mac, running macOS Mojave.
